development:
  adapter: mysql2
  database: <%= ENV['db_base'] %>
  encoding: utf8
  host: <%= ENV["db_host"] %>
  username: <%= ENV["db_user"] %>
  password: <%= ENV["db_pass"] %>

test:
  adapter: mysql2
  database: wcms_test
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:
