development:
  adapter: mysql2
  database: wcms_dev
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:

test:
  adapter: mysql2
  database: wcms_test
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:
