development:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  encoding: utf8
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: 


test:
  adapter: mysql2
  database: wcms_test
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:
