development:
  DB_HOST: 127.0.0.1
  DB_PASS: skate2cr8
  DB_USERNAME: root
  DB_NAME: wcms_dev
  BLIZZ_KEY: t3pbznutdmmqv52waukaxu9ankgqq9ne
  MANDRILL_USER: johannes.nyb@gmail.com
  MANDRILL_APIKEY: Xlhf5zPYNMe4wt2RHTu6Fg
